# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set up Dlang deps
      uses: dlang-community/setup-dlang@v1
      
    - name: Compile and set up hall_request_assigner
      run: scripts/install_deps.sh
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: |
        go test -v elevatorAlgorithm/hra
        go test -v requestSync/requestSync_test.go
